Parameters:

  Stage:
    Description: environment name
    Type: String
    AllowedValues:
      - CODE
      - PROD

Resources:

  PaymentFailureQueue:
    Type: AWS::SQS:Queue
    Properties:
      QueueName: !Sub PaymentFailureQueue${Stage}

  PaymentFailureLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: identity-lambda
        S3Key: !Sub identity/${Stage}/payment-failure-lambda/main.zip
      Description: Lambda to send emails to customers with a recurring payment plan whos card is about to expire
      Environment:
        Variables:
          Stage: !Sub ${Stage}
