AWSTemplateFormatVersion: 2010-09-09
Description: Stack to enable sending emails to customers with a recurring payment plan whos card is about to expire or failed

Parameters:
  Stage:
    Description: environment name
    Type: String
    AllowedValues:
      - CODE
      - PROD

Resources:
  PaymentFailureLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: PaymentFailureLambdaPolicy
        PolicyDocument:
          Statement:
            Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: '*'
  PaymentFailureLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: identity-lambda
        S3Key: !Sub identity/${Stage}/payment-failure-lambda/main.jar
      Description: Lambda to send emails to customers with a recurring payment plan whos card is about to expire or failed
      Environment:
        Variables:
          Stage: !Sub ${Stage}
      FunctionName: !Sub PaymentFailureLambda-${Stage}
      Handler: com.gu.identity.paymentfailure.Lambda::handler
      Role: !GetAtt PaymentFailureLambdaRole.Arn
      Runtime: java8
      Timeout: 60
