AWSTemplateFormatVersion: 2010-09-09
Description: Stack to enable sending emails to customers with a recurring payment plan whos card is about to expire or failed

Parameters:
  Stage:
    Description: environment name
    Type: String
    AllowedValues:
      - CODE
      - PROD

Mappings:
  StageMap:
    CODE:
      MembershipAppRole: arn:aws:iam::***REMOVED***:role/Workflow-CODE-MembershipAppRole-BR2CJ3AACTNY
    PROD:
      MembershipAppRole: arn:aws:iam::***REMOVED***:role/Workflow-MembershipAppRole-Q4O0MAAL9OB9

Resources:
  PaymentFailureLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: PaymentFailureLambdaPolicy
        PolicyDocument:
          Statement:
            Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:PaymentFailureLambda-${Stage}
      - PolicyName: PaymentFailureLambdaLoggingPolicy
        PolicyDocument:
          Statement:
            Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/PaymentFailureLambda-${Stage}:log-stream:*
      - PolicyName: PaymentFailureQueueReadPolicy
        PolicyDocument:
          Statement:
            Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Resource: !GetAtt PaymentFailureQueue.Arn

  PaymentFailureLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: identity-lambda
        S3Key: !Sub identity/${Stage}/payment-failure-lambda/main.jar
      Description: Lambda to send emails to customers with a recurring payment plan whos card is about to expire or failed
      Environment:
        Variables:
          Stage: !Sub ${Stage}
      FunctionName: !Sub PaymentFailureLambda-${Stage}
      Handler: com.gu.identity.paymentfailure.Lambda::handler
      Role: !GetAtt PaymentFailureLambdaRole.Arn
      Runtime: java8
      Timeout: 15

  PaymentFailureDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Stage}-payment-failure-dead-letter

  PaymentFailureQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub  ${Stage}-payment-failure
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PaymentFailureDeadLetterQueue.Arn
        maxReceiveCount: 5

  PaymentFailureSqsWriteRole:
    Type: AWS::SQS:QueuePolicy
    Properties:
      Queues: !Ref PaymentFailureQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Principal:
              AWS: !FindInMap [StageMap, !Sub ${Stage}, MembershipAppRole]
            Resource: !GetAtt PaymentFailureQueue.Arn

  PaymentFailureLambdaEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt PaymentFailureQueue.Arn
      FunctionName: !GetAtt PaymentFailureLambda.Arn
