name: CI - Payment failure lambda

on:
  pull_request:
    paths:
      - 'payment-failure/**'
      - '.github/workflows/ci-payment-failure.yml'
  push:
    branches:
      - main
    paths:
      - 'payment-failure/**'
      - '.github/workflows/ci-payment-failure.yml'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read        

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Test and build 
        run: sbt clean compile test assembly
        working-directory: payment-failure

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Upload to RiffRaff
        uses: guardian/actions-riff-raff@v2
        with:
          projectName: payment-failure-lambda
          buildNumberOffset: 271
          configPath: payment-failure/riff-raff.yaml
          contentDirectories: |
            payment-failure-lambda:
              - payment-failure/target/scala-2.12/main.jar
            payment-failure-cfn:
              - payment-failure/cloud-formation.yaml
