on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI:
    name: Deploy formstack-baton-requests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'
      - name: Build App
        working-directory: formstack-baton-requests
        run: sbt clean compile riffRaffUpload
      - name: Upload to Riff Raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: formstack-baton-requests
          buildNumberOffset: 203
          configPath: ./formstack-baton-requests/riff-raff.yaml
          dryRun: true
          contentDirectories: |
            cloudformation:
              - cfn.yaml
            eventbrite-baton-requests:
              - target/scala-2.12/eventbrite-baton-requests.jar
