name: Update Dependency Graph for SBT
on:
  push:
    branches:
      - main
      - sbt-dependency-graph-527bb4aadaeaf147
  workflow_dispatch:
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Submit dependencies
        id: submit-eventbrite-consents
        uses: scalacenter/sbt-dependency-submission@7ebd561e5280336d3d5b445a59013810ff79325e # v3.0.1
        with:
          working-directory: ./eventbrite-consents
      - name: Submit dependencies
        id: submit-formstack-baton-request
        uses: scalacenter/sbt-dependency-submission@7ebd561e5280336d3d5b445a59013810ff79325e # v3.0.1
        with:
          working-directory: ./formstack-baton-requests
      - name: Submit dependencies
        id: submit-formstack-consents
        uses: scalacenter/sbt-dependency-submission@7ebd561e5280336d3d5b445a59013810ff79325e # v3.0.1
        with:
          working-directory: ./formstack-consents
      - name: Submit dependencies
        id: submit-payment-failure
        uses: scalacenter/sbt-dependency-submission@7ebd561e5280336d3d5b445a59013810ff79325e # v3.0.1
        with:
          working-directory: ./payment-failure
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write
